name: Bomberman
main: io.github.mdsimmo.bomberman.Bomberman
version: ${version}
api-version: 1.15
load: POSTWORLD

commands:
  bomberman:
    description: Main command for Bomberman
    usage: bomberman <more commands>
    aliases: bm
    permission: bomberman.observer

depend: [WorldEdit]
softdepend: [Multiverse-Core, Vault]
  
permissions:
  bomberman.*:
    description: Gives access to all Bomberman commands
    children:
      bomberman.player: true
      bomberman.operator: true
      bomberman.dictator: true
  bomberman.player:
    description: Allows you to join/leave bomberman games
    default: true
  bomberman.operator:
    description: Allows you control games (eg, start/stop)
    default: op
  bomberman.dictator:
    description: Complete control over a bomberman game settings
    default: op
