name: Bomberman
main: io.github.mdsimmo.bomberman.Bomberman
version: 0.0.3

commands:
  create-game:
    description: generates a bomberman game
    usage: /create-game <game> [arena]
    permission: bomberman.op 
  destroy-game:
    description: destroys the game and reverts the land to how it was
    usage: /destroy-game <game>
    permission: bomberman.op
  reset-game:
    description: resets the game to the starting point
    usage: /reset-game <game> 
    permission: bomberman.op
  join-game:
    description: Places the player into the game
    usage: /join-game <game>
    permission: bomberman.player
  leave-game:
    description: Leave the currently joined game
    useage: /leave-game
    permission: bomberman.player
  start-game:
    description: Starts the game
    usage: /start-game <game>
    permission: bomberman.op
  stop-game:
    description: Stops the game
    usage: /stop-game <game>
    permission: bomberman.op
  arena:
    description: Sets the game's arena
    usage: /arena <game> [arena] 
    permission: bomberman.player
  lives:
    description: Sets the game's initial lives
    usage: /lives <game> [amount]
    permission: bomberman.player
  bombs:
    description: Sets the game's initial bombs
    usage: /bombs <game> [amount]
    permission: bomberman.player
  power:
    description: Sets the players' initial power
    usage: /power <game> [amount]
    permission: bomberman.player
  min-players:
    description: Sets the game's minimum players
    usage: /min-players <game> [amount]
    permission: bomberman.player
  autostart:
    description: If set to 'true', the game will start once the minimum amount of players have joined.
    usage: /autostart <game> <true|false>
    permission: bomberman.op
  create-arena:
    description: Makes the thing you're looking at a standard board arena
    usage: /create-arena <arena>
    permission: bomberman.op
  convert-to-game:
    description: converts the stucture being looked at into an arena
    usage: /convert-to-game <game>
    permission: bomberman.op
  list-games:
    description: List all games currently existing
    usage: /list-games
    permission: bomberman.player
  list-arenas:
    description: Lists all the arena currently available
    usage: /list-arenas
    permission: bomberman.player
  fare:
    description: Gets/sets what participants must pay to join a game
    usage: 
      - /fare <game> - gets the game's entry fare
      - /fare <game> <material> <amount> - set the game's entry fare
      - /fare <game> none - removes the game's entry fare
    permission: bomberman.player
  prize:
    description: Gets/sets the amount that the winner will receive. 
    usage:
      - /prize <game> - gets the game's current prize
      - /prize <game> pot - winner gets what the total of what the player's entry fare
      - /prize <game> <material> <amount> - winner gets a fixed amount
      - /prize <game> none - winner only gets the glory
    permission: bomberman.player
  info:
    description: Gets all the information about a game
    usage: /info <game>
    permission: bomberman.player
  
permissions:
  bomberman.*:
    description: Gives access to all Bomberman commands
    children:
      bomberman.op: true
      bomberman.player: true
  bomberman.player:
    description: Allows you to partake in the Bommerman fun
    default: true
  bomberman.op:
    description: Allows you to create and modify games
    default: op
