name: Bomberman
main: io.github.mdsimmo.bomberman.Bomberman
version: 0.0.3

commands:
  bm:
    description: Main command for BomberMan - contains all sub-commands.
    usage:
    - /<command>
    - /<command> game [...]
    - /<command> arena [...]
    permission: bomberman.observer
  
permissions:
  bomberman.*:
    description: Gives access to all Bomberman commands
    children:
      bomberman.observer: true
      bomberman.player: true
      bomberman.operator: true
      bomberman.dictator: true
      bomberman.arena: true
  bomberman.observer:
    description: Allows viewing of Bomberman information
    default: true
  bomberman.player:
    description: Allows you to join/leave bomberman games
    default: true
  bomberman.operator:
    description: Allows you control games (eg, start/stop)
    default: op
  bomberman.dictator:
    description: Complete control over a bomberman game settings
    default: op
  bomberman.arena:
    description: Create and edit arenas 
    default: op
  
    
  
